name: Run tests
on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        user: actions/checkout@v3.3.0
      - name: Setup Node.js enviroment
        user: actions/setup-node@3.6.0
        with:
          node-version: 16.13.x
          cache: yarn
      - name: Install dependencies
        run: |
          yarn cache clean
          yarn install --network-concurrency 1
      - name: Running tests
        run: yarn test
